### ISSUE TITLE
About SpeedNet: Learning the Speediness in Videos.

### ISSUE THREAD

**Issue by summersnowfish** [yasar-rehman/FEDVSSL#3]
Hi, I absolutely adore your work.
I recently read an article called SpeedNet: Learning the Speediness in Videos. When I looked for its code it pointed to your FEDVSSL working code on github. I would like to ask whether these two jobs are related?

**Comment by summersnowfish** [comment]
Sorry, I know now, you don't need to reply, thank you very much.

**Comment by yasar-rehman** [comment]
Hi @summersnowfish! 

Just to add, our implementation of SpeedNet is based on the following codes from the CtP repository: 

(1) https://github.com/microsoft/CtP/blob/main/pyvrl/models/pretraining/speednet/speednet_model.py 
(2) https://github.com/microsoft/CtP/blob/main/pyvrl/models/pretraining/speednet/speednet_dataset.py

Hope this can clarify some doubts. 

Best,

**Comment by summersnowfish** [comment]
Thank you very much for your reply.
Best wishes for you!
